[general]
import = ["/home/sentience/.cache/wal/colors.toml"]

[font]
size = 11

[font.normal]
family = "JetBrains Mono Nerd Font"
#family = "Rubik"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
opacity = 0.8

[window.padding]
x = 5
y = 0

