vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set number")

require("config.lazy")
require("config.colors")
require("config.treesitter")
require("config.telescope")
require("config.neo-tree")
require("config.lsp")
require("config.none_ls")
require("config.splash")
require("config.bar")
require("config.completions")
require("config.dap")
